videoSource: 0
useDisplay: true
displayScale: 0.7
inputSize: 224
clipSeconds: 2.0
sampleFps: 8
strideSeconds: 0.5

stageA:
    enabled: true
    modelName: x3d_m
    checkpointPath: "weights/x3d_finetuned_packed.pth"
    device: "cuda:0"
    threshold: 0.50

stageB:
    enabled: false
    modelName: slowfast_r50
    checkpointPath: "weights/x3d_finetuned_packed.pth"
    device: "cuda:1"
    threshold: 0.85

decision:
    alertOn: 0.8
    clearOn: 0.35
    minRaiseSeconds: 1.0
    minClearSeconds: 3.0

personGate:
    enabled: false
    minPersonArea: 0.02

roi:
    enabled: false
    polygon: []

logging:
    level: "info"
    saveAlertsMp4: false
    alertSnippetsSeconds: 8
    outputDir: "runs"
